---
title: "¿Por qué estudiar la Maestría en Negocios Agroalimentarios?"
subtitle: Universidad Nacional del Litoral
output:
  html_document:
    css: mna.css
    includes:
      after_body: footermna.html
      before_body: headermna.html
editor_options: null
---

Porque el futuro necesita profesionales aptos para dirigir los negocios de empresas y organizaciones del sector agroalimentario con una visión estratégica e integral, capaces de conformar equipos interdisciplinarios y enfrentar los desafíos de un entorno globalizado que cambia en forma permanente, contribuyendo al desarrollo territorial de formas rentables y cuidando a su vez la conservación de los recursos naturales, el medioambiente y las personas.

Para ello, entre las Facultades de Ciencias Agrarias y Ciencias Económicas de la Universidad Nacional del Litoral, diseñamos una carrera con un cursado compartido entre docentes de ambas unidades académicas que aportan conocimientos, experiencias y miradas diferentes desde sus disciplinas que enriquecen la formación.

Es una maestría profesional, pensada para mejorar tus competencias ya sea para la dirección de una organización agroalimentaria o para ocupar cargos gerenciales o desarrollar su propio emprendimiento. Con un diseño flexible en el que se completa la formación con asignaturas optativas, algunas con cursado en la Facultad de Ciencias Agrarias y otras en la Facultad de Ciencias Económicas compartiendo la experiencia con alumnos de la Maestría en Administración.
